import type { Branch, BranchPromo, Chain, Promo } from "./types";

const DEMO_TERMS =
  "Folio ilustrativo de TraGo. La sucursal sí existe en Guadalajara; el precio y la vigencia se confirman en el local. No es una promoción oficial de la cadena.";

export const CATALOG_VERSION = 3;

export const chains: Chain[] = [
  {
    id: "c1",
    slug: "la-europea",
    name: "La Europea",
    tagline: "Vinos y licores",
    description: "Cadena real. Sucursales Andares y Chapalita en la ZMG.",
    mark: "LE",
    markColor: "#7a1f2b",
    website: "https://www.laeuropea.com.mx",
    tier: "premium",
    publishesPromos: true,
    hasApiAccess: true,
    showAds: false,
  },
  {
    id: "c2",
    slug: "oxxo",
    name: "OXXO",
    tagline: "Conveniencia",
    description: "Sucursales reales en Americana y Chapultepec, Guadalajara.",
    mark: "OX",
    markColor: "#c45c12",
    website: "https://www.oxxo.com",
    tier: "free",
    publishesPromos: true,
    hasApiAccess: false,
    showAds: true,
  },
  {
    id: "c3",
    slug: "karne-garibaldi",
    name: "Karne Garibaldi",
    tagline: "Carnes · Guadalajara",
    description: "Restaurante emblemático en Mexicaltzingo. Promos de comida y cumpleaños de demo.",
    mark: "KG",
    markColor: "#8b2e1a",
    website: "https://www.karnegaribaldi.com.mx",
    tier: "pro",
    publishesPromos: true,
    hasApiAccess: false,
    showAds: false,
  },
  {
    id: "c4",
    slug: "italiannis",
    name: "Italianni's",
    tagline: "Italiana",
    description: "Centro Magno, Vallarta. Combos y postre de cumpleaños ilustrativos.",
    mark: "IT",
    markColor: "#2d5a3d",
    website: "https://www.italiannis.com.mx",
    tier: "pro",
    publishesPromos: true,
    hasApiAccess: false,
    showAds: false,
  },
  {
    id: "c5",
    slug: "vips",
    name: "VIPS",
    tagline: "Familiar",
    description: "Plaza del Sol. Desayunos y regalo de cumpleaños de demo.",
    mark: "VP",
    markColor: "#b42318",
    website: "https://www.vips.com.mx",
    tier: "free",
    publishesPromos: true,
    hasApiAccess: false,
    showAds: true,
  },
  {
    id: "c6",
    slug: "gallo-altanero",
    name: "El Gallo Altanero",
    tagline: "Bar",
    description: "Av. México, Ladrón de Guevara. Happy hour y shot de cumpleaños de demo.",
    mark: "GA",
    markColor: "#1a3d36",
    website: "https://www.instagram.com/elgalloaltanero/",
    tier: "pro",
    publishesPromos: true,
    hasApiAccess: false,
    showAds: false,
  },
  {
    id: "c7",
    slug: "nueve-esquinas",
    name: "Las 9 Esquinas",
    tagline: "Birria",
    description: "Colón, Mexicaltzingo. Combo de birria ilustrativo.",
    mark: "9E",
    markColor: "#5c2e16",
    website: "https://www.las9esquinas.com",
    tier: "free",
    publishesPromos: true,
    hasApiAccess: false,
    showAds: true,
  },
  {
    id: "c8",
    slug: "starbucks",
    name: "Starbucks",
    tagline: "Café",
    description: "Chapultepec, Americana. Bebida de cumpleaños de demo (no Rewards oficial).",
    mark: "SB",
    markColor: "#1e3932",
    website: "https://www.starbucks.com.mx",
    tier: "free",
    publishesPromos: true,
    hasApiAccess: false,
    showAds: true,
  },
];

export const branches: Branch[] = [
  {
    id: "b1",
    slug: "europea-andares",
    chainId: "c1",
    name: "La Europea Andares",
    kind: "licoreria",
    address: "Av. Acueducto 6075, Puerta de Hierro",
    colonia: "Puerta de Hierro",
    city: "Zapopan",
    geo: { lat: 20.7108, lng: -103.4116 },
    hours: "11:00 – 21:00",
    imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&h=500&fit=crop",
  },
  {
    id: "b2",
    slug: "europea-chapalita",
    chainId: "c1",
    name: "La Europea Chapalita",
    kind: "licoreria",
    address: "Av. Guadalupe 1675",
    colonia: "Chapalita",
    city: "Zapopan",
    geo: { lat: 20.6664, lng: -103.4008 },
    hours: "10:00 – 20:00",
    imageUrl: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800&h=500&fit=crop",
  },
  {
    id: "b3",
    slug: "oxxo-chapultepec",
    chainId: "c2",
    name: "OXXO Chapultepec",
    kind: "tienda",
    address: "Av. Chapultepec 120",
    colonia: "Americana",
    city: "Guadalajara",
    geo: { lat: 20.6738, lng: -103.3762 },
    hours: "24 h",
    imageUrl: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800&h=500&fit=crop",
  },
  {
    id: "b4",
    slug: "oxxo-lopez-cotilla",
    chainId: "c2",
    name: "OXXO López Cotilla",
    kind: "tienda",
    address: "Av. López Cotilla 1479",
    colonia: "Americana",
    city: "Guadalajara",
    geo: { lat: 20.6746, lng: -103.3715 },
    hours: "24 h",
    imageUrl: "https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=800&h=500&fit=crop",
  },
  {
    id: "b5",
    slug: "karne-garibaldi-mexicaltzingo",
    chainId: "c3",
    name: "Karne Garibaldi",
    kind: "restaurante",
    address: "Calle Garibaldi 1306",
    colonia: "Mexicaltzingo",
    city: "Guadalajara",
    geo: { lat: 20.6638, lng: -103.3524 },
    hours: "08:00 – 18:00",
    imageUrl: "https://images.unsplash.com/photo-1558030006-450675393462?w=800&h=500&fit=crop",
  },
  {
    id: "b6",
    slug: "italiannis-centro-magno",
    chainId: "c4",
    name: "Italianni's Centro Magno",
    kind: "restaurante",
    address: "Av. Vallarta 2425",
    colonia: "Arcos Vallarta",
    city: "Guadalajara",
    geo: { lat: 20.6749, lng: -103.3878 },
    hours: "13:00 – 23:00",
    imageUrl: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800&h=500&fit=crop",
  },
  {
    id: "b7",
    slug: "vips-plaza-del-sol",
    chainId: "c5",
    name: "VIPS Plaza del Sol",
    kind: "restaurante",
    address: "Av. López Mateos Sur 2375",
    colonia: "Ciudad del Sol",
    city: "Zapopan",
    geo: { lat: 20.6508, lng: -103.4019 },
    hours: "07:00 – 23:00",
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=500&fit=crop",
  },
  {
    id: "b8",
    slug: "gallo-altanero-mexico",
    chainId: "c6",
    name: "El Gallo Altanero",
    kind: "bar",
    address: "Av. México 2770",
    colonia: "Ladrón de Guevara",
    city: "Guadalajara",
    geo: { lat: 20.6846, lng: -103.3768 },
    hours: "18:00 – 02:00",
    imageUrl: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800&h=500&fit=crop",
  },
  {
    id: "b9",
    slug: "nueve-esquinas-colon",
    chainId: "c7",
    name: "Las 9 Esquinas",
    kind: "restaurante",
    address: "Calle Colón 384",
    colonia: "Mexicaltzingo",
    city: "Guadalajara",
    geo: { lat: 20.6662, lng: -103.3501 },
    hours: "08:00 – 18:00",
    imageUrl: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&h=500&fit=crop",
  },
  {
    id: "b10",
    slug: "starbucks-chapultepec",
    chainId: "c8",
    name: "Starbucks Chapultepec",
    kind: "cafe",
    address: "Av. Chapultepec 238",
    colonia: "Americana",
    city: "Guadalajara",
    geo: { lat: 20.6741, lng: -103.3751 },
    hours: "07:00 – 22:00",
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=500&fit=crop",
  },
];

export const promos: Promo[] = [
  {
    id: "p1",
    slug: "europea-3x2-mezcal",
    chainId: "c1",
    title: "3x2 en mezcal seleccionado",
    subtitle: "Botella 750 ml · Andares y Chapalita",
    kind: "botella",
    isNocturno: true,
    alcohol: true,
    isBirthday: false,
    startsAt: "2026-08-01T00:00:00-06:00",
    endsAt: "2026-12-31T23:59:59-06:00",
    terms: DEMO_TERMS,
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1d?w=900&h=600&fit=crop",
    featured: true,
    isDemo: true,
  },
  {
    id: "p2",
    slug: "oxxo-2x1-cerveza",
    chainId: "c2",
    title: "2x1 en cerveza lata",
    subtitle: "18:00 a 22:00 · Americana",
    kind: "2x1",
    isNocturno: true,
    alcohol: true,
    isBirthday: false,
    startsAt: "2026-08-01T00:00:00-06:00",
    endsAt: "2026-12-31T23:59:59-06:00",
    terms: DEMO_TERMS,
    imageUrl: "https://images.unsplash.com/photo-1608270586620-248804b7740e?w=900&h=600&fit=crop",
    featured: true,
    isDemo: true,
  },
  {
    id: "p3",
    slug: "garibaldi-arrachera",
    chainId: "c3",
    title: "Arrachera 2x1 al mediodía",
    subtitle: "De 13:00 a 16:00 · Mexicaltzingo",
    kind: "comida",
    isNocturno: false,
    alcohol: false,
    isBirthday: false,
    startsAt: "2026-08-01T00:00:00-06:00",
    endsAt: "2026-12-31T23:59:59-06:00",
    terms: DEMO_TERMS,
    imageUrl: "https://images.unsplash.com/photo-1558030006-450675393462?w=900&h=600&fit=crop",
    featured: true,
    isDemo: true,
  },
  {
    id: "p4",
    slug: "garibaldi-cumple",
    chainId: "c3",
    title: "Postre de cumpleaños",
    subtitle: "Te lo regalan el día de tu cumple · con ID",
    kind: "cumple",
    isNocturno: false,
    alcohol: false,
    isBirthday: true,
    startsAt: "2026-01-01T00:00:00-06:00",
    endsAt: "2026-12-31T23:59:59-06:00",
    terms: `${DEMO_TERMS} Presenta identificación. Solo el día de tu cumpleaños.`,
    imageUrl: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=900&h=600&fit=crop",
    featured: true,
    isDemo: true,
  },
  {
    id: "p5",
    slug: "italiannis-pasta",
    chainId: "c4",
    title: "Pasta + ensalada",
    subtitle: "Combo de mediodía · Centro Magno",
    kind: "comida",
    isNocturno: false,
    alcohol: false,
    isBirthday: false,
    startsAt: "2026-08-01T00:00:00-06:00",
    endsAt: "2026-12-31T23:59:59-06:00",
    terms: DEMO_TERMS,
    imageUrl: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=900&h=600&fit=crop",
    featured: false,
    isDemo: true,
  },
  {
    id: "p6",
    slug: "italiannis-cumple",
    chainId: "c4",
    title: "Tiramisú de cumpleaños",
    subtitle: "Regalo el día de tu cumple",
    kind: "regalo",
    isNocturno: false,
    alcohol: false,
    isBirthday: true,
    startsAt: "2026-01-01T00:00:00-06:00",
    endsAt: "2026-12-31T23:59:59-06:00",
    terms: `${DEMO_TERMS} Un postre por mesa. El cumpleañero debe estar presente.`,
    imageUrl: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=900&h=600&fit=crop",
    featured: true,
    isDemo: true,
  },
  {
    id: "p7",
    slug: "vips-desayuno",
    chainId: "c5",
    title: "Desayuno 2x1",
    subtitle: "Lunes a viernes hasta las 12:00",
    kind: "2x1",
    isNocturno: false,
    alcohol: false,
    isBirthday: false,
    startsAt: "2026-08-01T00:00:00-06:00",
    endsAt: "2026-12-31T23:59:59-06:00",
    terms: DEMO_TERMS,
    imageUrl: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=900&h=600&fit=crop",
    featured: true,
    isDemo: true,
  },
  {
    id: "p8",
    slug: "vips-cumple",
    chainId: "c5",
    title: "Hotcakes de regalo",
    subtitle: "El día de tu cumpleaños en VIPS",
    kind: "cumple",
    isNocturno: false,
    alcohol: false,
    isBirthday: true,
    startsAt: "2026-01-01T00:00:00-06:00",
    endsAt: "2026-12-31T23:59:59-06:00",
    terms: `${DEMO_TERMS} Consulta si piden app o INE.`,
    imageUrl: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?w=900&h=600&fit=crop",
    featured: true,
    isDemo: true,
  },
  {
    id: "p9",
    slug: "gallo-happy-hour",
    chainId: "c6",
    title: "Happy hour de barra",
    subtitle: "18:00 a 21:00 · Av. México",
    kind: "happy-hour",
    isNocturno: true,
    alcohol: true,
    isBirthday: false,
    startsAt: "2026-08-01T00:00:00-06:00",
    endsAt: "2026-12-31T23:59:59-06:00",
    terms: DEMO_TERMS,
    imageUrl: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=900&h=600&fit=crop",
    featured: true,
    isDemo: true,
  },
  {
    id: "p10",
    slug: "gallo-cumple",
    chainId: "c6",
    title: "Shot de cumpleaños",
    subtitle: "Te lo regalan en barra el día de tu cumple",
    kind: "regalo",
    isNocturno: true,
    alcohol: true,
    isBirthday: true,
    startsAt: "2026-01-01T00:00:00-06:00",
    endsAt: "2026-12-31T23:59:59-06:00",
    terms: `${DEMO_TERMS} 18+. Identificación en puerta.`,
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1d?w=900&h=600&fit=crop",
    featured: false,
    isDemo: true,
  },
  {
    id: "p11",
    slug: "nueve-esquinas-birria",
    chainId: "c7",
    title: "Combo birria + consomé",
    subtitle: "Hasta las 16:00 · Colón",
    kind: "comida",
    isNocturno: false,
    alcohol: false,
    isBirthday: false,
    startsAt: "2026-08-01T00:00:00-06:00",
    endsAt: "2026-12-31T23:59:59-06:00",
    terms: DEMO_TERMS,
    imageUrl: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=900&h=600&fit=crop",
    featured: true,
    isDemo: true,
  },
  {
    id: "p12",
    slug: "starbucks-cumple",
    chainId: "c8",
    title: "Bebida de cumpleaños",
    subtitle: "Grande de regalo el día de tu cumple",
    kind: "cumple",
    isNocturno: false,
    alcohol: false,
    isBirthday: true,
    startsAt: "2026-01-01T00:00:00-06:00",
    endsAt: "2026-12-31T23:59:59-06:00",
    terms: `${DEMO_TERMS} En la app real suele pedirse Rewards; aquí es folio ilustrativo.`,
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=900&h=600&fit=crop",
    featured: true,
    isDemo: true,
  },
];

export const branchPromos: BranchPromo[] = [
  { promoId: "p1", branchId: "b1", officialActive: true, reportsVigente: 9, reportsCaduco: 1 },
  { promoId: "p1", branchId: "b2", officialActive: true, reportsVigente: 3, reportsCaduco: 5 },
  { promoId: "p2", branchId: "b3", officialActive: true, reportsVigente: 14, reportsCaduco: 2 },
  { promoId: "p2", branchId: "b4", officialActive: true, reportsVigente: 2, reportsCaduco: 8 },
  { promoId: "p3", branchId: "b5", officialActive: true, reportsVigente: 18, reportsCaduco: 1 },
  { promoId: "p4", branchId: "b5", officialActive: true, reportsVigente: 6, reportsCaduco: 0 },
  { promoId: "p5", branchId: "b6", officialActive: true, reportsVigente: 7, reportsCaduco: 1 },
  { promoId: "p6", branchId: "b6", officialActive: true, reportsVigente: 11, reportsCaduco: 0 },
  { promoId: "p7", branchId: "b7", officialActive: true, reportsVigente: 10, reportsCaduco: 2 },
  { promoId: "p8", branchId: "b7", officialActive: true, reportsVigente: 15, reportsCaduco: 1 },
  { promoId: "p9", branchId: "b8", officialActive: true, reportsVigente: 12, reportsCaduco: 1 },
  { promoId: "p10", branchId: "b8", officialActive: true, reportsVigente: 8, reportsCaduco: 0 },
  { promoId: "p11", branchId: "b9", officialActive: true, reportsVigente: 16, reportsCaduco: 0 },
  { promoId: "p12", branchId: "b10", officialActive: true, reportsVigente: 20, reportsCaduco: 3 },
];
